controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    myactuator_rmd_state_broadcaster:
      type: myactuator_rmd_state_broadcaster/MyActuatorRmdStateBroadcaster

    effort_controller:
      type: forward_command_controller/ForwardCommandController

    position_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


effort_controller:
  ros__parameters:
    joints:
      - joint
    interface_name: effort

position_controller:
  ros__parameters:
    joints:
      - joint
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - joint
    interface_name: velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.1
